### ISSUE TITLE
terraform-provider-healthchecksio

### ISSUE THREAD

**Issue by c33s** [arthur-leclerc/arthur-leclerc#1]
any chance that you reenable the repo again?
https://github.com/arthur-leclerc/terraform-provider-healthchecksio

**Comment by arthur-leclerc** [comment]
Hello,

Take a look at the [official project](https://registry.terraform.io/providers/kristofferahl/healthchecksio/latest), I had simply pushed the version `v1.6.0` on the registry when the official project was not yet available on it.

**Comment by c33s** [comment]
as i stumpled upon this again, would it be possible that you delete your provider from the terraform registry?

**Comment by arthur-leclerc** [comment]
Unfortunately there is no official way to do so and my email to Hashicorp went unanswered.

**Comment by c33s** [comment]
thanks for the feedback
